apiVersion: v1
kind: Service
metadata:
  name: svc-3mtt-capstone-by-obomeghie2019-service
spec:
  type: ClusterIP
  selector:
    app: 3mtt-capstone-by-obomeghie2019
  ports:
    - port: 80
      targetPort: 3000